### ISSUE TITLE
请教一个kryo序列化的问题

### ISSUE THREAD

**Issue by supreme94** [apache/incubator-dubbo-spring-boot-project#157]
想用kryo去序列化，请问是这样用吗？
```yaml
dubbo:
    protocol:
      id: dubbo
      name: dubbo
      port: 12345
      status: server
      serialization: kryo
```
启动的时候报错了
> 2018-06-04 17:14:39.952 ERROR 2020 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target com.alibaba.boot.dubbo.autoconfigure.SingleDubboConfigBindingProperties@360bc645 failed:

    Property: dubbo.protocol.serialization
    Value: kryo
    Reason: Property 'protocol.serialization' threw exception; nested exception is java.lang.IllegalStateException: No such extension kryo for serialization/com.alibaba.dubbo.common.serialize.Serialization

Action:

Update your application's configuration
