### ISSUE TITLE
配置文件不支持spring占位符address: zookeeper://${zk.host}:${zk.port}解析

### ISSUE THREAD

**Issue by sunlightzy** [apache/incubator-dubbo-spring-boot-project#289]
yml文件内容
```yaml
dubbo:
  registry:
    address: zookeeper://${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
```
无法正常解析,ZK_HOST和ZK_PORT是环境变量
报错信息 `java.lang.NumberFormatException: For input string: 127.0.0.1}:${ZK_PORT:2181}`
