### ISSUE TITLE
注册不到zookeeper

### ISSUE THREAD

**Issue by zhucj94** [apache/incubator-dubbo-spring-boot-project#292]
yml
```
dubbo: 
  scan:
    base-packages: com.zjy.log.service.dubboProducer
  registry:
    address: zookeeper://localhost:2181
  application:
    name: logDubboService
    id: logDubboService
  protocol:
    name: dubbo
    id: dubbo
    port: 20884
```
class
```
package com.zjy.log.service.dubboProducer;

@Service(application = "${dubbo.application.id}", protocol = "${dubbo.protocol.id}")
public class LogDubboServiceImpl implements LogDubboService {
	@Override
	public void xxx(param) {
		System.out.println("123456");
	}
}
```
LogDubboService在其他jar里面
