### ISSUE TITLE
协议配置default(protocol.default=true)不起作用

### ISSUE THREAD

**Issue by Lzw2016** [apache/incubator-dubbo-spring-boot-project#311]
### 配置如下
```
dubbo:
  application: #------------------------------------------------------ dubbo应用配置
    id: SpringDubboProvider
    name: SpringDubboProvider
  registry: #----------------------------------------------------------- 注册中心配置
    id: zk-registry
    protocol: zookeeper
    address: 127.0.0.1:2181
    default: true
    client: curator
    transporter: netty
    check: true
    register: true
    subscribe: true
    dynamic: true
    group: dev-group
  protocol: #-------------------------------------------------------------- 协议配置
    id: dubbo
    name: dubbo
    port: 20881
    default: true
```
设置服务暴露端口 `20881`

### 版本如下
```
       <dependency>
                <groupId>com.alibaba.boot</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>0.2.0</version>
            </dependency>
```

### 代码如下
```
@Service
public class DefaultDemoService implements DemoService {

    @Override
    public String sayHello(String name) {
        return "Hello, " + name + " (from Spring Boot)";
    }
}
```
