### ISSUE TITLE
Dubbo 配置项不支持引用配置

### ISSUE THREAD

**Issue by ganpengyu** [apache/incubator-dubbo-spring-boot-project#32]
如下配置：

```yml
dubbo:
  scan:
    base-packages: com.xxx.saas.module.service.demo
  application:
    id: order-provider-demo
    name: order-provider-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: xxx-registry
    address: ${zookeeper.address}
```

启动报错：

```yml
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://${zookeeper.address}:9090/com.alibaba.dubbo.registry.RegistryService
```

类似的如下配置：

```yml
spring:
  application:
    name: order-provider-demo

dubbo:
  scan:
    base-packages: com.xxx.saas.module.service.demo
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
```

启动也会报错找不到名为 `order-provider-demo` 的 Bean。

观察发现，对于第一个例子，是没有对引用的变量进行解析而导致的。

对于第二个例子就比较费解了。引用的变量已经被解析了，但这时报错说找不到对应的 Bean。如果这里不引用变量，直接写死，那么又不会出错。
