### ISSUE TITLE
Log warn repetition on 0.2.1

### ISSUE THREAD

**Issue by leokoon** [apache/incubator-dubbo-spring-boot-project#411]
I changed the version from 0.2.0 to 0.2.1， then I got the log warn
```
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
application.yml
```
dubbo:
  application:
    name: esgcc-tc-core-cart-his-service
    id: esgcc-tc-core-cart-his-service
    logger: slf4j
```
