### ISSUE TITLE
已经禁用了qos还是报错呢。 qos-enable: false 这个配置似乎无效

### ISSUE THREAD

**Issue by penweizgx** [apache/incubator-dubbo-spring-boot-project#423]
生产和消费都已经禁用了qos还是报错呢。 qos-enable: false 这个配置似乎无效
<img width="567" alt="wx20190117-192059 2x" src="https://user-images.githubusercontent.com/6983487/51315460-31386080-1a8d-11e9-9e9c-de63280ffec6.png">
<img width="615" alt="wx20190117-192658 2x" src="https://user-images.githubusercontent.com/6983487/51315762-e703af00-1a8d-11e9-9487-4931d33e28b1.png">

_Originally posted by @penweizgx in https://github.com/apache/incubator-dubbo-spring-boot-project/issues/394#issuecomment-455137711_
![1548819081094](https://user-images.githubusercontent.com/6983487/51957015-d50a0f00-2484-11e9-9851-3e50b5ac3f8c.jpg)

**Comment by mercyblitz** [comment]
Which version do you used?

**Comment by penweizgx** [comment]
> Which version do you used?

`<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>`

**Comment by mercyblitz** [comment]
that's a legacy issue, please Update the lastest one : 

```xml
<dependency>
      <groupId>com.alibaba.boot</groupId>
     <artifactId>dubbo-spring-boot-starter</artifactId>
     <version>0.2.1.RELEASE</version>
</dependency>
```

**Comment by foreveryang321** [comment]
2.7.1 the same problem
```xml
<dependency>
      <groupId>com.alibaba.boot</groupId>
     <artifactId>dubbo-spring-boot-starter</artifactId>
     <version>0.2.1.RELEASE</version>
</dependency>
```
> the wrong configuration
```yaml
dubbo:
  application:
    name: dubbo-spring-cloud-provider
    qos-enable: false
    qos-port: 33333
    qos-accept-foreign-ip: false
```
> the correct configuration
```yaml
dubbo:
  application:
    name: dubbo-spring-cloud-provider
    qos:
       enable: false
       port: 33333
       accept:
         foreign:
           ip: false
```
