### ISSUE TITLE
为什么AutoConfiguration不生效，需要手动@EnableDubbo

### ISSUE THREAD

**Issue by linux-chaina** [apache/incubator-dubbo-spring-boot-project#462]
依赖版本：0.2.0

启动类：
```java
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

yml配置

```yaml
dubbo:
  application:
    name: test
    owner: test
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: x.springboot.dubbo.provider.api   # 这里配置的是实现类的包路径
```

问题是为什么
`com.alibaba.boot.dubbo.autoconfigure.DubboAutoConfiguration` 为什么不生效，
况且你这里都默认true
` @ConditionalOnProperty(prefix = DUBBO_PREFIX, name = "enabled", matchIfMissing = true, havingValue = "true")` 

然而还是需要我手动在启动类上加  `@EnableDubbo`  才能能效，wtf？？？尼克扬表情~
谁来解释下？

而且即使通过配置这个也没用：
```
dubbo.enabled: true
```
只有使用`@EnableDubbo` 或者`@DubboComponentScan({"手动指定包才生效, wtf?"})`
