### ISSUE TITLE
dubbo的provider和comsumer属性配置不生效

### ISSUE THREAD

**Issue by foreveryang321** [apache/incubator-dubbo-spring-boot-project#60]
dubbo-spring-boot-starter.0.1.0.jar
```yml
dubbo:
  application:
    name: demo
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
    client: curator
  provider:
    version: 1.0
    timeout: 20000
    retries: 0
  consumer:
    version: 1.0
    timeout: 20000
    retries: 0
    check: false
```
其中protocol.port，provider和consumer配置均不生效

不知道是否与PropertySourcesUtils类中只会把String类型的属性放到subProperties中有关？
![dubbo](https://user-images.githubusercontent.com/5868190/37391475-3caeed24-27a6-11e8-807a-97462ccf76df.png)

数值通过加单引号（''），能够正确获取到值。
从这个看，数值类型，boolean值类型的配置都不会生效

**Comment by levin950825** [comment]
我也被这问题困扰着

**Comment by luffyke** [comment]
Duplicated with #30

**Comment by mercyblitz** [comment]
Next release will resolve this issue

**Comment by lovepoem** [comment]
Now https://github.com/alibaba/dubbo/milestone/13 is released. dubbo 2.6.1 has fixed this bug

You can manually modify the Dubbo version to 2.6.1 first

**Comment by foreveryang321** [comment]
OK, Thanks

**Comment by foreveryang321** [comment]
application.yml
```yml
dubbo:
  consumer:
    check: false
```
调用ConfigUtils.replaceProperty(properties.getProperty(key, defaultValue), (Map) properties)读取配置时，返回 null，java.util.Properties.getProperty源码如下

![image](https://user-images.githubusercontent.com/5868190/42026035-aa059c2e-7af8-11e8-8b6f-80ca38a3d128.png)
